   drop table IF EXISTS items CASCADE;
   drop table IF EXISTS users CASCADE;
   drop table IF EXISTS bookings CASCADE;
   drop table IF EXISTS comments CASCADE;
create TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(512) NOT NULL,
    constraint uq_user_email unique (email)
);

create TABLE IF NOT EXISTS items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(1024) NOT NULL,
    is_available BOOLEAN,
    owner_id BIGINT NOT NULL,
CONSTRAINT fk_items_owner_id FOREIGN KEY(owner_id)
    REFERENCES users(id)
);

create TABLE IF NOT EXISTS bookings (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
start_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
end_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
item_id BIGINT NOT NULL,
booker_id BIGINT NOT NULL,
status VARCHAR(255),
CONSTRAINT fk_bookings_item_id FOREIGN KEY(item_id)
    REFERENCES items(id),
CONSTRAINT fk_bookings_booker_id FOREIGN KEY(booker_id)
    REFERENCES users(id)
);

create TABLE IF NOT EXISTS comments (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
text VARCHAR(1024) NOT NULL,
item_id BIGINT NOT NULL,
author_id BIGINT NOT NULL,
created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
CONSTRAINT fk_comments_item_id FOREIGN KEY(item_id)
    REFERENCES items(id),
CONSTRAINT fk_comments_author_id FOREIGN KEY(author_id)
    REFERENCES users(id)
);
